version: '2'

services:

  maintenancev2:
    build: .
    image: maintenancev2
    container_name: maintenancev2
    restart: always
    environment:
      APP_KEY: 'base64:4EWpH9R4Nn0UaYKLebweZFnRRxbeNuXbvf/Ttit9wLM='
      APP_DEBUG: 'false'
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: db_maintenance
      DB_USERNAME: root
      DB_PASSWORD: root@hsj@2328
    volumes:
      - ./maintenancev2/public:/app/public
    ports:
      - 6217:8282
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysqls_mntv2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@hsj@2328
      MYSQL_DATABASE: db_maintenance
    ports:
      - 3311:3306
    volumes:
      - mysqls_mntv2:/var/lib/mysql

networks:
  default:


volumes:
  mysqls_mntv2:


